package org.drools.ansible.rulebook.integration.ha.postgres;

import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.ACTION_INFO;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.HA_STATS;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.IDX_ACTION_INFO_ME;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.IDX_MATCHING_EVENT_HA_UUID;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.MATCHING_EVENT;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.SESSION_STATE;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * PostgreSQL database schema creation and management
 */
public class PostgreSQLSchema {

    private static final Logger logger = LoggerFactory.getLogger(PostgreSQLSchema.class);

    public static void createSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setAutoCommit(false);

            // Create session state table
            // PostgreSQL differences from H2:
            // - BIGSERIAL instead of BIGINT GENERATED BY DEFAULT AS IDENTITY
            // - TEXT instead of CLOB
            String createSessionStateTable =
                    "CREATE TABLE IF NOT EXISTS " + SESSION_STATE + " ("
                    + "id BIGSERIAL PRIMARY KEY, "
                    + "ha_uuid VARCHAR(255) NOT NULL, "
                    + "rule_set_name VARCHAR(255) NOT NULL, "
                    + "rulebook_hash VARCHAR(64), "
                    + "partial_matching_events TEXT, "
                    + "persisted_time TIMESTAMP, "
                    + "current_state_sha VARCHAR(64), "
                    + "version INT DEFAULT 1, "
                    + "created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                    + "leader_id VARCHAR(255), "
                    + "UNIQUE(ha_uuid, rule_set_name, version)"
                    + ")";
            stmt.execute(createSessionStateTable);

            // Create MatchingEvent table
            // PostgreSQL differences from H2:
            // - UUID instead of VARCHAR(36) for native UUID support
            // - TEXT instead of CLOB
            String createMatchingEventTable =
                    "CREATE TABLE IF NOT EXISTS " + MATCHING_EVENT + " ("
                    + "me_uuid UUID PRIMARY KEY, "
                    + "ha_uuid VARCHAR(255) NOT NULL, "
                    + "rule_set_name VARCHAR(255), "
                    + "rule_name VARCHAR(255) NOT NULL, "
                    + "event_data TEXT, "
                    + "created_at BIGINT DEFAULT 0"
                    + ")";
            stmt.execute(createMatchingEventTable);

            // Create ActionInfo table
            // PostgreSQL differences from H2:
            // - UUID instead of VARCHAR(36) for native UUID support
            // - TEXT instead of CLOB
            String createActionInfoTable =
                    "CREATE TABLE IF NOT EXISTS " + ACTION_INFO + " ("
                    + "id UUID PRIMARY KEY, "
                    + "ha_uuid VARCHAR(255) NOT NULL, "
                    + "me_uuid UUID NOT NULL, "
                    + "index INT NOT NULL, "
                    + "action_data TEXT, "
                    + "UNIQUE(me_uuid, index), "
                    + "FOREIGN KEY (me_uuid) REFERENCES " + MATCHING_EVENT + "(me_uuid) ON DELETE CASCADE"
                    + ")";
            stmt.execute(createActionInfoTable);

            String createMatchingEventIndex =
                    "CREATE INDEX IF NOT EXISTS " + IDX_MATCHING_EVENT_HA_UUID
                    + " ON " + MATCHING_EVENT + "(ha_uuid)";
            stmt.execute(createMatchingEventIndex);

            String createActionInfoIndex =
                    "CREATE INDEX IF NOT EXISTS " + IDX_ACTION_INFO_ME
                    + " ON " + ACTION_INFO + "(me_uuid)";
            stmt.execute(createActionInfoIndex);

            // Create HA stats table
            // PostgreSQL differences from H2:
            // - BIGSERIAL instead of BIGINT GENERATED BY DEFAULT AS IDENTITY
            String createHAStatsTable =
                    "CREATE TABLE IF NOT EXISTS " + HA_STATS + " ("
                    + "id BIGSERIAL PRIMARY KEY, "
                    + "ha_uuid VARCHAR(255) NOT NULL, "
                    + "current_leader VARCHAR(255), "
                    + "leader_switches INT DEFAULT 0, "
                    + "current_term_started_at VARCHAR(255), "
                    + "events_processed_in_term INT DEFAULT 0, "
                    + "actions_processed_in_term INT DEFAULT 0, "
                    + "partial_events_in_memory INT DEFAULT 0, "
                    + "incomplete_matching_events INT DEFAULT 0, "
                    + "global_session_stats TEXT, "
                    + "partial_fulfilled_rules INT DEFAULT 0, "
                    + "session_state_size BIGINT DEFAULT 0, "
                    + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                    + "UNIQUE(ha_uuid)"
                    + ")";
            stmt.execute(createHAStatsTable);

            conn.commit();
            logger.info("PostgreSQL schema creation completed successfully");
        }
    }

    public static void dropSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setAutoCommit(false);

            // Drop in reverse order due to foreign keys
            stmt.execute("DROP TABLE IF EXISTS " + ACTION_INFO + " CASCADE");
            stmt.execute("DROP TABLE IF EXISTS " + MATCHING_EVENT + " CASCADE");
            stmt.execute("DROP TABLE IF EXISTS " + SESSION_STATE + " CASCADE");
            stmt.execute("DROP TABLE IF EXISTS " + HA_STATS + " CASCADE");

            conn.commit();
            logger.info("PostgreSQL schema dropped successfully");
        }
    }
}
