package org.drools.ansible.rulebook.integration.ha.postgres;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * PostgreSQL database schema creation and management
 */
public class PostgreSQLSchema {

    private static final Logger logger = LoggerFactory.getLogger(PostgreSQLSchema.class);

    public static void createSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setAutoCommit(false);

            // Create session state table
            // PostgreSQL differences from H2:
            // - BIGSERIAL instead of BIGINT GENERATED BY DEFAULT AS IDENTITY
            // - TEXT instead of CLOB
            String createSessionStateTable = """
                    CREATE TABLE IF NOT EXISTS SessionState (
                        id BIGSERIAL PRIMARY KEY,
                        ha_uuid VARCHAR(255) NOT NULL,
                        rule_set_name VARCHAR(255) NOT NULL,
                        rulebook_hash VARCHAR(64),
                        partial_matching_events TEXT,
                        time_windows TEXT,
                        persisted_time TIMESTAMP,
                        current_state_sha VARCHAR(64),
                        version INT DEFAULT 1,
                        created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        leader_id VARCHAR(255),
                        UNIQUE(ha_uuid, rule_set_name, version)
                    )
                    """;
            stmt.execute(createSessionStateTable);

            // Create MatchingEvent table
            // PostgreSQL differences from H2:
            // - UUID instead of VARCHAR(36) for native UUID support
            // - TEXT instead of CLOB
            String createMatchingEventTable = """
                    CREATE TABLE IF NOT EXISTS MatchingEvent (
                        me_uuid UUID PRIMARY KEY,
                        ha_uuid VARCHAR(255) NOT NULL,
                        rule_set_name VARCHAR(255),
                        rule_name VARCHAR(255) NOT NULL,
                        event_data TEXT
                    )
                    """;
            stmt.execute(createMatchingEventTable);

            // Create ActionInfo table
            // PostgreSQL differences from H2:
            // - UUID instead of VARCHAR(36) for native UUID support
            // - TEXT instead of CLOB
            String createActionInfoTable = """
                    CREATE TABLE IF NOT EXISTS ActionInfo (
                        id UUID PRIMARY KEY,
                        me_uuid UUID NOT NULL,
                        index INT NOT NULL,
                        action_data TEXT,
                        UNIQUE(me_uuid, index),
                        FOREIGN KEY (me_uuid) REFERENCES MatchingEvent(me_uuid) ON DELETE CASCADE
                    )
                    """;
            stmt.execute(createActionInfoTable);

            String createMatchingEventIndex = """
                    CREATE INDEX IF NOT EXISTS idx_matching_event_ha_uuid
                    ON MatchingEvent(ha_uuid)
                    """;
            stmt.execute(createMatchingEventIndex);

            String createActionInfoIndex = """
                    CREATE INDEX IF NOT EXISTS idx_action_info_me
                    ON ActionInfo(me_uuid)
                    """;
            stmt.execute(createActionInfoIndex);

            // Create HA stats table
            // PostgreSQL differences from H2:
            // - BIGSERIAL instead of BIGINT GENERATED BY DEFAULT AS IDENTITY
            String createHAStatsTable = """
                    CREATE TABLE IF NOT EXISTS HAStats (
                        id BIGSERIAL PRIMARY KEY,
                        ha_uuid VARCHAR(255) NOT NULL,
                        current_leader VARCHAR(255),
                        leader_switches INT DEFAULT 0,
                        current_term_started_at VARCHAR(255),
                        events_processed_in_term INT DEFAULT 0,
                        actions_processed_in_term INT DEFAULT 0,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(ha_uuid)
                    )
                    """;
            stmt.execute(createHAStatsTable);

            conn.commit();
            logger.info("PostgreSQL schema creation completed successfully");
        }
    }

    public static void dropSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setAutoCommit(false);

            // Drop in reverse order due to foreign keys
            stmt.execute("DROP TABLE IF EXISTS ActionInfo CASCADE");
            stmt.execute("DROP TABLE IF EXISTS MatchingEvent CASCADE");
            stmt.execute("DROP TABLE IF EXISTS SessionState CASCADE");
            stmt.execute("DROP TABLE IF EXISTS HAStats CASCADE");

            conn.commit();
            logger.info("PostgreSQL schema dropped successfully");
        }
    }
}
