package org.drools.ansible.rulebook.integration.ha.h2;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * H2 database schema creation and management
 */
public class H2Schema {

    private static final Logger logger = LoggerFactory.getLogger(H2Schema.class);

    public static void createSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            // Create event state table (unchanged - still needed for session state)
            String createEventStateTable = """
                    CREATE TABLE IF NOT EXISTS EventState (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id VARCHAR(255) NOT NULL,
                        rulebook_hash VARCHAR(64),
                        partial_matching_events CLOB,
                        time_windows CLOB,
                        clock_time TIMESTAMP,
                        session_stats CLOB,
                        version INT DEFAULT 1,
                        is_current BOOLEAN DEFAULT FALSE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        leader_id VARCHAR(255),
                        UNIQUE(session_id, version)
                    )
                    """;
            stmt.execute(createEventStateTable);
            logger.debug("Created/verified EventState table");

            // Create MatchingEvent table (renamed and restructured)
            String createMatchingEventTable = """
                    CREATE TABLE IF NOT EXISTS MatchingEvent (
                        me_uuid VARCHAR(36) PRIMARY KEY,
                        session_id VARCHAR(255) NOT NULL,
                        rule_set_name VARCHAR(255),
                        rule_name VARCHAR(255) NOT NULL,
                        event_data CLOB
                    )
                    """;
            stmt.execute(createMatchingEventTable);
            logger.debug("Created/verified MatchingEvent table");

            // Create ActionState table (renamed and restructured - single action per record)
            String createActionStateTable = """
                    CREATE TABLE IF NOT EXISTS ActionState (
                        id VARCHAR(36) PRIMARY KEY,
                        me_uuid VARCHAR(36) NOT NULL,
                        index INT NOT NULL,
                        action_data CLOB,
                        UNIQUE(me_uuid, index),
                        FOREIGN KEY (me_uuid) REFERENCES MatchingEvent(me_uuid) ON DELETE CASCADE
                    )
                    """;
            stmt.execute(createActionStateTable);
            logger.debug("Created/verified ActionState table");

            // Create indexes for better query performance
            String createEventStateIndex = """
                    CREATE INDEX IF NOT EXISTS idx_event_state_session 
                    ON EventState(session_id, is_current)
                    """;
            stmt.execute(createEventStateIndex);

            String createMatchingEventIndex = """
                    CREATE INDEX IF NOT EXISTS idx_matching_event_session 
                    ON MatchingEvent(session_id)
                    """;
            stmt.execute(createMatchingEventIndex);

            String createActionStateIndex = """
                    CREATE INDEX IF NOT EXISTS idx_action_state_me 
                    ON ActionState(me_uuid)
                    """;
            stmt.execute(createActionStateIndex);

            // Create HA stats table (unchanged)
            String createHAStatsTable = """
                    CREATE TABLE IF NOT EXISTS HAStats (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id VARCHAR(255) NOT NULL,
                        current_leader VARCHAR(255),
                        leader_switches INT DEFAULT 0,
                        current_term_started_at VARCHAR(255),
                        events_processed_in_term INT DEFAULT 0,
                        actions_processed_in_term INT DEFAULT 0,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(session_id)
                    )
                    """;
            stmt.execute(createHAStatsTable);
            logger.debug("Created/verified HAStats table");

            conn.commit();
            logger.info("H2 schema creation completed successfully");
        }
    }

    public static void dropSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            // Drop in reverse order due to foreign keys
            stmt.execute("DROP TABLE IF EXISTS ActionState");
            stmt.execute("DROP TABLE IF EXISTS MatchingEvent");
            stmt.execute("DROP TABLE IF EXISTS EventState");
            stmt.execute("DROP TABLE IF EXISTS HAStats");

            conn.commit();
            logger.info("H2 schema dropped successfully");
        }
    }
}